# Dongle is always USB-powered, no sleep needed
CONFIG_ZMK_USB=y
CONFIG_ZMK_BLE=y

# Full N-Key Rollover
CONFIG_ZMK_HID_REPORT_TYPE_NKRO=y

# ZMK Studio (live keymap editing over USB)
CONFIG_ZMK_STUDIO=y

# Fetch peripheral battery levels for the USB battery interface
CONFIG_ZMK_SPLIT_BLE_CENTRAL_BATTERY_LEVEL_FETCHING=y
